sitebetaver/imgpro_app/urls.py
from django.urls import path
from imgpro_app import views

app_name = 'imgpro_app'

urlpatterns = [
    path('', views.HomeImg, name='homeImg'),
    path('imgpro/', views.ImgPro, name='imgPro'),
    path('home/', views.NewHomeImg, name='homeImg2'),
]

sitebetaver/sitebetaver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main_app import views

urlpatterns = [
    path ('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('image/', include('imgpro_app.urls')),
    path('user/', include('user_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitebetaver/user_app/urls.py
from django.urls import path
from user_app import views

app_name = 'user_app'

urlpatterns = [
    path('', views.HomeUser, name='user_home'),
    path('login/', views.LoginView, name='user_login'),
    path('logout/', views.LogoutView, name='user_logout'),
    path('registration/', views.RegistrationView, name='registration')
]

sitebetaver/imgpro_app/models.py
from django.db import models
import os

# Create your models here.

class TBImage(models.Model):
    slideNumber = models.CharField(max_length=60)
    def_path = "img/"+str(slideNumber)+"/default/"
    pro_path = "img/"+str(slideNumber)+"/processed/"
    imgDefault = models.ImageField(upload_to=def_path,null=True, blank=True)
    imgProcessed = models.ImageField(upload_to=pro_path,null=True, blank=True)

sitebetaver/main_app/models.py
from django.db import models

# Create your models here.

sitebetaver/user_app/models.py
from django.db import models

# Create your models here.

sitebetaver/imgpro_app/forms.py
from django import forms
from imgpro_app.models import TBImage

class TBImageForm(forms.ModelForm):
    """Form definition for TBImage."""

    class Meta:
        """Meta definition for TBImageform."""

        model = TBImage
        fields = ('imgDefault',)
        labels = {'imgDefault':''}

sitebetaver/imgpro_app/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from imgpro_app.process import ImageEqualizer as imgEQ
from imgpro_app.models import TBImage
from imgpro_app.forms import TBImageForm

# Create your views here.
def HomeImg(request):
    if request.method == 'POST' and request.FILES['imgDefault']:
        myfile = request.FILES['imgDefault']
        fs = FileSystemStorage()
        filename = fs.save('image_input.jpg', myfile)
        uploaded_file_url = fs.path(filename)
        image = imgEQ(uploaded_file_url)
        uploaded_file_url = fs.url(filename)
        img_src_url = {'defImg':uploaded_file_url, 'proImg':image}
        return render(request, 'imgpro_app/img_pro.html', context=img_src_url)
    return render(request, 'imgpro_app/home_img.html', {'form':TBImageForm})

def ImgPro(request):
    return render(request, 'imgpro_app/img_pro.html')

def NewHomeImg(request):
    form = TBImageForm(data=request.POST or None)
    if request.POST == 'POST' and form.is_valid():
        img = form.save(commit=False)
        imgProcessed = request.FILES['imgProcessed'].name()
        print(imgProcessed)
        return render(request, 'imgpro_app/home_img.html', {'form':TBImageForm})
    return render(request, 'imgpro_app/home_img.html', {'form':TBImageForm})

sitebetaver/main_app/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'main_app/home.html')

sitebetaver/user_app/views.py
from django.shortcuts import render

# Create your views here.
def HomeUser (request):
    return render(request, 'user_app/home_user.html')

def LoginView (request):
    return render(request, 'user_app/login.html')

def LogoutView (request):
    return render(request, 'user_app/logut.html')

def RegistrationView (request):
    return render(request, 'user_app/registration.html')

sitebetaver/imgpro_app/templates/imgpro_app/home_img.html
{% extends 'base_nav.html' %}

{% block title_block %}
    Image Home
{% endblock title_block %}


{% block body_block %}
<br>
<div class='jumbotron' style="background-color: #f7d217">
    <h1>Welcome to Image Home Page</h1>
    <h3>please enjoy your visit</h3>
</div>

<div class='form-group jumbotron text-center' style="background-color: whitesmoke">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="upload_gambar">Masukkan gambar yang diinginkan</label>
        <br>
        {{form.as_p}}
        <br>
        <button class="btn btn-primary" type="submit">Upload</button>
    </form>
</div>
{% endblock body_block %}

sitebetaver/imgpro_app/templates/imgpro_app/img_base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
        crossorigin="anonymous">
    <title>
        {% block title_block %} {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #06337b">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home'%}">
                <img src='{% static "logo-uii.png" %}' height="30" class="d-inline-block align-top" alt="">
                Home
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarLogin" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarLogin">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'imgpro_app:homeImg' %}">Image Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'imgpro_app:imgPro' %}">Process</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Slightly Different</a>
                </li>
                </ul>
                <div class="btn-group dropleft">
                    <button class="btn btn-outline-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Login
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <form class="px-4 py-3">
                            <div class="form-group">
                              <label for="login-username">Username</label>
                              <input type="text" class="form-control" id="login-username" placeholder="Username">
                            </div>
                            <div class="form-group">
                              <label for="login-password">Password</label>
                              <input type="password" class="form-control" id="login-password" placeholder="Password">
                            </div>
                            <div class="form-group">
                              <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="dropdownCheck">
                                <label class="form-check-label" for="dropdownCheck">
                                  Remember me
                                </label>
                              </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Sign in</button>
                        </form>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">New around here? Sign up</a>
                        <a class="dropdown-item" href="#">Forgot password?</a>
                    </div>
                </div>
                
                <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form> -->
            </div>
        </div>
    </nav>
    <div class='container-md jumbotron jumbotron-fluid'>
        {% block body_block %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" 
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
        crossorigin="anonymous"></script>
</body>
</html>

sitebetaver/imgpro_app/templates/imgpro_app/img_pro.html
{% extends 'base_nav.html' %}
{% load staticfiles %}

{% block title_block %}
    Image Process
{% endblock title_block %}


{% block body_block %}
<br>
<div class='jumbotron' style="background-color: #f7d217">
    <h1>Welcome to Image Process Page</h1>
    <h3>here, your image will be processed and waiting for the result</h3>
</div>
<div class="container">
    <div class="row jumbotron" align="center">
      <div class="col-sm">
        <img src="{{ defImg }}" alt="We are sorry, something went wrong" width="400">
        <p>Preprocessed Image</p>
      </div>
      <div class="col-sm">
        <img src="{{ proImg }}" alt="We are sorry, something went wrong" width="400">
        <p>Processed Image</p>
      </div>
    </div>
  </div>
{% endblock body_block %}

sitebetaver/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
        crossorigin="anonymous">
    <title>
        {% block title_block %} {% endblock %}
    </title>
</head>
<body>
    
    {% block nav_block %}
        
    {% endblock nav_block %}
        
    <div class='container-md jumbotron jumbotron-fluid'>
        {% block body_block %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" 
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
        crossorigin="anonymous"></script>
</body>
</html>

sitebetaver/templates/base_nav.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block nav_block %}
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #06337b">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home'%}">
                <img src='{% static "logo-uii.png" %}' height="30" class="d-inline-block align-top" alt="">
                Home
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarLogin" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarLogin">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'imgpro_app:homeImg' %}">Image Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'imgpro_app:imgPro' %}">Process</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
                </ul>
                <div class="btn-group dropleft">
                    <button class="btn btn-outline-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Login
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <form class="px-4 py-3">
                            <div class="form-group">
                              <label for="login-username">Username</label>
                              <input type="text" class="form-control" id="login-username" placeholder="Username">
                            </div>
                            <div class="form-group">
                              <label for="login-password">Password</label>
                              <input type="password" class="form-control" id="exampleDropdownFormPassword1" placeholder="Password">
                            </div>
                            <div class="form-group">
                              <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="dropdownCheck">
                                <label class="form-check-label" for="dropdownCheck">
                                  Remember me
                                </label>
                              </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Sign in</button>
                        </form>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">New around here? Sign up</a>
                        <a class="dropdown-item" href="#">Forgot password?</a>
                    </div>
                </div>
                
                <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form> -->
            </div>
        </div>
    </nav>
{% endblock nav_block %}
    

sitebetaver/templates/main_app/home.html
{% extends 'base_nav.html' %}

{% block title_block %}
    Home
{% endblock title_block %}


{% block body_block %}
<br>
<div class='jumbotron' style="background-color: #f7d217">
    <h1>Welcome to Adnan Site</h1>
    <h3>Please enjoy your visit</h3>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">You might want to see</h5>
            <p class="card-text">A new content was added a while ago and you might want to review it.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">You might want to see</h5>
            <p class="card-text">A new content was added a while ago and you might want to review it.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
    </div>
</div>
{% endblock body_block %}
    
    

sitebetaver/user_app/templates/user_app/user_base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
        crossorigin="anonymous">
    <title>
        {% block title_block %} {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #06337b">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home'%}">
                <img src='{% static "logo-uii.png" %}' height="30" class="d-inline-block align-top" alt="">
                Home
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarLogin" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarLogin">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'imgpro_app:homeImg' %}">Image Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'imgpro_app:imgPro' %}">Process</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
                </ul>
                <div class="btn-group dropleft">
                    <button class="btn btn-outline-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Login
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <form class="px-4 py-3">
                            <div class="form-group">
                              <label for="login-username">Username</label>
                              <input type="text" class="form-control" id="login-username" placeholder="Username">
                            </div>
                            <div class="form-group">
                              <label for="login-password">Password</label>
                              <input type="password" class="form-control" id="exampleDropdownFormPassword1" placeholder="Password">
                            </div>
                            <div class="form-group">
                              <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="dropdownCheck">
                                <label class="form-check-label" for="dropdownCheck">
                                  Remember me
                                </label>
                              </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Sign in</button>
                        </form>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">New around here? Sign up</a>
                        <a class="dropdown-item" href="#">Forgot password?</a>
                    </div>
                </div>
                
                <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form> -->
            </div>
        </div>
    </nav>
    <div class='container-md jumbotron jumbotron-fluid'>
        {% block body_block %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" 
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
        crossorigin="anonymous"></script>
</body>
</html>